// Command icons regenerates icon/generated.go with a Name constant per
// embedded heroicon. Run from the repository root:
//
//	go run ./cmd/icons
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"

	"github.com/pietjan/loom/internal/assets"
)

func main() {
	names, err := assets.IconNames("outline")
	if err != nil {
		log.Fatal(err)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/icons; DO NOT EDIT.\n\n")
	buf.WriteString("package icon\n\n")
	buf.WriteString("const (\n")
	for _, name := range names {
		fmt.Fprintf(&buf, "\t%s Name = %q\n", constName(name), name)
	}
	buf.WriteString(")\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("icon/generated.go", formatted, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("icon/generated.go: %d icons\n", len(names))
}

// constName converts a file name like "academic-cap" to "AcademicCap".
func constName(name string) string {
	var out strings.Builder
	for _, part := range strings.Split(name, "-") {
		if part == "" {
			continue
		}
		out.WriteString(strings.ToUpper(part[:1]))
		out.WriteString(part[1:])
	}
	return out.String()
}
