// Command css writes the Tailwind entry file for a project using loom.
// Run it inside the user's module (it resolves loom's on-disk location via
// `go list`):
//
//	go run github.com/pietjan/loom/cmd/css -accent indigo -o assets/css/input.css
//
// The output imports Tailwind, imports loom's structural CSS, points
// @source at loom's Go sources in the module cache (so the Tailwind CLI
// sees the class strings baked into the components), and embeds the
// generated theme variables. The @source path is version-pinned: re-run
// after upgrading loom (a //go:generate directive is a natural home).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	_ "embed"

	"github.com/pietjan/loom/cmd/css/internal/theme"
)

//go:embed loom.css
var loomCSS []byte

func main() {
	accent := flag.String("accent", "zinc", "accent color (any Tailwind palette name)")
	base := flag.String("base", "", "neutral base palette override (slate, gray, zinc, neutral, stone)")
	out := flag.String("o", "", "output file (default: stdout)")
	flag.Parse()

	moduleDir, err := loomDir()
	if err != nil {
		log.Fatal(err)
	}

	opts := []theme.Option{theme.WithAccent(*accent)}
	if *base != "" {
		opts = append(opts, theme.WithBase(*base))
	}
	themeCSS, err := theme.Generate(opts...)
	if err != nil {
		log.Fatal(err)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "/* Generated by github.com/pietjan/loom/cmd/css — re-run after upgrading loom. */\n")
	fmt.Fprintf(&buf, "@import \"tailwindcss\";\n")
	fmt.Fprintf(&buf, "@source %q;\n\n", moduleDir)
	buf.Write(themeCSS)
	buf.Write(loomCSS)

	if *out == "" {
		os.Stdout.Write(buf.Bytes())
		return
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, buf.Bytes(), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s (accent=%s)\n", *out, *accent)
}

// loomDir resolves loom's on-disk directory in the current module's
// dependency graph (module cache, or a local replace/workspace path).
func loomDir() (string, error) {
	cmd := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "github.com/pietjan/loom")
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("resolving loom module dir (are you inside your project module?): %w", err)
	}
	dir := strings.TrimSpace(string(out))
	if dir == "" {
		return "", fmt.Errorf("go list returned no directory for github.com/pietjan/loom")
	}
	return dir, nil
}
